### ISSUE TITLE
Contao 4.11 - Abhängigkeiten

### ISSUE THREAD

**Issue by katgirl** [erdmannfreunde/sirius-theme-bundle#1]
Das Paket lässt sich nicht in einem neu aufgesetzten Contao installieren, da die Abhängigkeiten zum Core der einzelnen Pakete wie z.B. euf_contact nicht erfüllen lassen.

**Comment by denniserdmann** [comment]
Geht es hierbei auch um die Symfony 5 Kompatibilität? Ich hätte erwartet, dass dann einfach ein Downgrade auf Symfony 4.4 gemacht werden würde.

@richardhj Hast du eine Idee?

**Comment by richardhj** [comment]
Ich sehe keine Dependency in diesem Paket, die problemhaft ist. Sicherlich müssten wir bei den anderen Erweiterungen die Versions-Constraints bearbeiten. Contao 4.11 ist mit Symfony 4 und 5 kompatibel.

**Comment by katgirl** [comment]
Die Dependency waren auch nicht in dem Paket, da dieses aber bereits für 4.11 freigegeben war hat es bei mir mächtig gescheppert ;-)
Danke Euch beiden für die schnelle Umsetzung.

Wenn man von Contao 4.10.X nach 4.11 geht, dann bleibt symfony noch auf der 4 stehen. Setzt man das aber neu auf, wird gleich die symfony 5 genommen, was dazu führte das die Erweiterungen sich nicht mehr haben installieren lassen.
Ein Downgrade wirddann leider nicht gemacht, wäre vielleicht vorübergehend ne interessante Lösung ;-) Aber das muss dann in den Core.
